# Generated by Django 3.2.8 on 2021-10-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecogApi',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('image', models.CharField(db_column='IMAGE', max_length=100)),
                ('id', models.CharField(db_column='ID', max_length=45)),
                ('gender', models.IntegerField(blank=True, db_column='GENDER', null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('company', models.CharField(db_column='COMPANY', max_length=100)),
            ],
            options={
                'db_table': 'FACE_RECOG_API',
                'managed': False,
            },
        ),
    ]
